//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESB2DatabaseContainer : DbContext
    {
        public ESB2DatabaseContainer()
            : base("name=ESB2DatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLogEvent> UserLog { get; set; }
        public virtual DbSet<EquipmentSystem> EquipmentSystems { get; set; }
        public virtual DbSet<EquipmentGrouping> EquipmentGroupings { get; set; }
        public virtual DbSet<Equipment> EquipmentListing { get; set; }
        public virtual DbSet<Outage> Outages { get; set; }
        public virtual DbSet<OutageUpdate> OutageUpdates { get; set; }
        public virtual DbSet<StatusPageGrouping> StatusPageGroupings { get; set; }
        public virtual DbSet<StatusPage> StatusPages { get; set; }
    }
}
