//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    
    public enum UserEvents : int
    {
        AccountCreated = 0,
        UserLogin = 1,
        UserLogout = 2,
        FailedLogin = 3,
        AccountLocked = 4,
        AccountUnlocked = 5,
        AccountDisabled = 6,
        PasswordChanged = 7
    }
}
